const COMMENTS_PER_PORTION = 5;

const PHOTO_COUNT = 25;
const AVATAR_COUNT = 6;
const LIKE_MIN = 15;
const LIKE_MAX = 200;
const COMMENT_COUNT = 15;
const MIN_MESSAGE = 1;
const MAX_MESSAGE = 2;

const MAX_HASHTAG_NUMBER = 5;
const VALID_SIMBOLS = /^#[a-zа-яё0-9]{1,19}/i;
const TAG_ERROR_TEXT = 'Неправельно заполнены хаштэги';


export {
  COMMENTS_PER_PORTION,
  PHOTO_COUNT,
  LIKE_MIN,
  LIKE_MAX,
  AVATAR_COUNT,
  COMMENT_COUNT,
  MIN_MESSAGE,
  MAX_MESSAGE,
  MAX_HASHTAG_NUMBER,
  VALID_SIMBOLS,
  TAG_ERROR_TEXT,
};
